### ISSUE TITLE
load_variables with 2000 census results in errors

### ISSUE THREAD

**Issue by Lawlzasaurusrex** [walkerke/tidycensus#300]
Hi there - looking for some help. Use of the following (my API key blinded here):

`library(tidycensus)
census_api_key("XXXX", install = TRUE, overwrite = TRUE)
variables <- load_variables(2000, "sf1", cache = FALSE)`

Results in the following:

`> variables <- load_variables(2000, "sf1", cache = FALSE)
Error in open.connection(x, "rb") : HTTP error 404.`

I would just use the 2000 sf1 codebook instead, but when I do that I get another error (below) that, from another thread, indicates the variable names have been updated in the API:

`varsH  <- c("H011001", "H011A002", "H011B002", "H011C002", "H011D002", "H011E002", "H011H002")
national_House <- get_decennial(geography = "county", variables = varsH, year = 2000, state = NULL, summary_var = "P001001")`

`> national_House <- get_decennial(geography = "county", variables = varsH, year = 2000, state = NULL, summary_var = "P001001") 
Getting data from the 2000 decennial Census
Error : Your API call has errors.  The API message returned is <html><head><title>Error report</title></head><body><h1>HTTP Status 404 - /data/2000/sf3</h1></body></html>.
Error in gather_(data, key_col = compat_as_lazy(enquo(key)), value_col = compat_as_lazy(enquo(value)),  : 
  unused argument (-NAME)`

**Comment by Lawlzasaurusrex** [comment]
I have now seen the pinned message. I tried using the github version: remotes::install_github("walkerke/tidycensus") and I am still having the same issue with both.

**Comment by walkerke** [comment]
thanks for the heads-up!  I just pushed a fix to GitHub so if you re-install `load_variables()` will now work.  The second issue is likely because you are trying to get SF3 variables for 2000, for which the API endpoint has been removed by Census.  We're all hoping for a fix to this soon!

**Comment by Lawlzasaurusrex** [comment]
That fixed my issue with load_variables. However, the second one still persists - sf3 was just a typo, I am using sf1.

Doing some testing, it looks like the issue may be something different: When I try each variable individually, I can pull the data successfully. However, when I do it combined (c("x")), I get the error.

See below:

`
> varsH  <- c("H011A002") 
> national_House <- get_decennial(
+                   geography = "county",
+                   variables = varsH,
+                   dataset = "sf1",
+                   year = 2000
+                   ) 
Getting data from the 2000 decennial Census
Using Census Summary File 1
> varsH  <- c("H011B002")
> national_House <- get_decennial(
+                   geography = "county",
+                   variables = varsH,
+                   dataset = "sf1",
+                   year = 2000
+                   ) 
Getting data from the 2000 decennial Census
Using Census Summary File 1
> varsH  <- c("H011C002")
> national_House <- get_decennial(
+                   geography = "county",
+                   variables = varsH,
+                   dataset = "sf1",
+                   year = 2000
+                   ) 
Getting data from the 2000 decennial Census
Using Census Summary File 1
> varsH  <- c("H011D002")
> national_House <- get_decennial(
+                   geography = "county",
+                   variables = varsH,
+                   dataset = "sf1",
+                   year = 2000
+                   ) 
Getting data from the 2000 decennial Census
Using Census Summary File 1
> varsH  <- c("H011E002")
> national_House <- get_decennial(
+                   geography = "county",
+                   variables = varsH,
+                   dataset = "sf1",
+                   year = 2000
+                   ) 
Getting data from the 2000 decennial Census
Using Census Summary File 1
> varsH  <- c("H011H002")
> national_House <- get_decennial(
+                   geography = "county",
+                   variables = varsH,
+                   dataset = "sf1",
+                   year = 2000
+                   ) 
Getting data from the 2000 decennial Census
Using Census Summary File 1
> varsH  <- c("H011001","H011A002","H011B002","H011C002","H011D002","H011E002","H011H002")
> national_House <- get_decennial(
+                   geography = "county",
+                   variables = varsH,
+                   dataset = "sf1",
+                   year = 2000
+                   ) 
Getting data from the 2000 decennial Census
Error : Your API call has errors.  The API message returned is <html><head><title>Error report</title></head><body><h1>HTTP Status 404 - /data/2000/sf3</h1></body></html>.
Variables not found in Summary File 1. Trying Summary File 3...
Error in gather_(data, key_col = compat_as_lazy(enquo(key)), value_col = compat_as_lazy(enquo(value)),  : 
  unused argument (-NAME)



`
